---
title: "Sustainability?"
format: html
---
Where do the concept, mission statement, and guiding principles of sustainable development come from? How did the concept emerge, how did it evolve – and why? The following explanations provide an overview of the history of sustainability, the political background, and key conferences and documents. In short, what has made sustainability what it is today. It’s about seeing the big picture. Because only those who know the past can assess the future.
Sustainability has been the buzzword of recent years, from science to politics and business to the media. Initially, the term has a positive connotation because it is associated with the long term, the durable, and many things are sustainable today: coffee, corporate philosophy, even tuna pizzas. These are the demands of a consumer society with an inconsiderate appetite for abundance. First thing in the morning, the shampoo removes our dandruff “sustainably”. Then we drive to work at a company that prides itself on its “sustainable corporate philosophy”, and over lunch we discuss sustainable investments. At home, we stick a tuna pizza in the oven – sustainably sourced and produced, of course, as it says on the box.
Today, the term “sustainability” is everywhere: it’s used in connection with energy, mobility, building renovation, nutrition, population development, corporate environmental management, and climate protection. It’s also used in art, culture, design, and advertising.

# A normative concept

To achieve sustainability, we need sustainable development: a strategic process that requires changes in our socio-ecological systems and institutions. “Development” implies controlled improvement, and the ethical question of what exactly “better” means is key. The use of the term “development” has been criticized by some (e.g. Lang et al. 2014; Kothari et al. 2019), as it is often equated with unbridled growth. Unbridled growth of the “ecological footprint” – the proportion of the biosphere used for human production, consumption, and waste – is unsustainable in the long term. Nonetheless, there are different interpretations of “development”, ranging from economic growth to improving quality of life. Sustainable development therefore remains a stimulating and controversial concept. Sustainability and sustainable development play a key role in today’s political discourse. The term “unsustainability” refers to conditions or developments that are considered negative, while “sustainability” represents a positive state.

The concept of sustainable development commits us to certain values and norms that define ethical goals and rules of behaviour. These values and norms shape our ideas of what we consider a desirable or “positive” change. A neutral point of view is not possible, as our perceptions are shaped by a variety of influences. Our personal experiences, upbringing, social environment, and cultural background all influence how we see and interpret the world, including our perceptions of what “should be” and what actions “should be taken”. Ethics play a key role in determining how the current situation can be improved to achieve sustainability, by defining normative goals and limits. Sustainable development is therefore a conceptual framework that is strongly driven by ethical considerations.

Sustainability challenges such as poverty reduction and climate change are therefore ethical challenges. The identification of situations as sustainability problems (and therefore as “negative”) and the choice of solutions are based on ethical values. Sustainability goals are also based on ethical values, as well as on knowledge of cause-and-effect relationships. Sustainability issues are often referred to as “wicked problems”, because of their complex and pluralistic nature. Global warming, in particular, has been described as a “super wicked problem”, as finding solutions is urgent, political institutions are often inadequate, and decision-making processes suffer from short-sightedness.

## Global challenges as wicked problems

Mike Hulme, author of Why We Disagree About Climate Change (2009), suggests that we view climate change as a “wicked problem” of enormous scale and likely longevity. This approach helps us see climate change not as a problem that needs to be solved, but as a condition in which we are directly involved. The categorization of problems as “wicked”, i.e. those that do not lend themselves to clear-cut solutions, originated with the planning theorists Horst Rittl and Melvin Webber (1973). They argued that planners have to deal with unpredictable human behaviour, and that some problems are too complicated to be solved completely. Some “wicked problems” may never be fully solved, but we can learn to cope with them and not let them dominate us.

::: {.callout-note collapse="true" appearance="minimal"}
#### Wicked problems

According to Bannink and Trommel (2019), wicked problems arise at the intersection of factual uncertainty and a heterogeneity of preferences and interests. Wicked problems are characterized by (Rittel & Weber, 1973; Alford, 2017; Sediri, 2020):

-   Complexity: Wicked problems are characterized by many interrelated factors and interactions. There are no clear cause-and-effect relationships, and changes in one area can have unforeseen effects in other areas.

-   Normative conflicts: Wicked problems are perceived and interpreted differently by different stakeholders and interest groups. There is no clear definition or consensus on what exactly the problem is, or how it should be solved.

-   Interdisciplinarity: Wicked problems require an interdisciplinary approach as they involve different topics, perspectives, and stakeholders. Finding a solution often requires the cooperation and coordination of different disciplines and experts. Uncertainty: Incorrect, missing, or inaccessible information about the problem situation and about the continuity of the values of the variables involved.

-   No definitive solution: Wicked problems defy clear-cut solutions. They are dynamic, change over time, and require continuous adjustment and iterations. Examples of wicked problems include climate change, poverty alleviation, global health, and sustainability. The complexity and interaction of different factors in these areas make it difficult to find simple and clear-cut solutions. Dealing with wicked problems requires a high degree of reflection, collaboration, and the use of systemic thinking methods.
:::

How have we manoeuvred ourselves into the current situation, where wicked problems pose such a challenge to sustainable development? In this textbook, we will analyse and learn to understand three key global challenges:

-   the emergence of human-induced global warming;

-   the persistence of global poverty and rising inequalities;

-   and the threat of species extinction and overexploitation of natural resources.

The debate about human influence on global warming and climate change has intensified since the publications of the Intergovernmental Panel on Climate Change (IPCC). The driving force behind global warming is our dependence on oil and other fossil fuels for transport, (electricity) generation, agriculture, and many everyday products. Another wicked problem is global poverty. Although there have been global efforts to reduce poverty for decades, the globalized market economy often leads to increased poverty in certain regions, and the gap between rich and poor seems to be widening overall (Chancel et al., 2021). High-income countries have maintained their prosperity and living standards at the expense of others. These are “externalized costs”, and they include environmental degradation. For example, the wealth and living standards of high-income countries are largely responsible for the threat of species extinction and the overuse of natural resources (Lessenich, 2018). In addition to the abovementioned “big three” – climate change, poverty, and biodiversity loss – there are many other global sustainability challenges, such as deforestation, desertification, declining soil fertility, dwindling fish stocks, pollution, wars, conflicts, and increasing migration. In analysing these comprehensive challenges we must also consider the temporal dimension. In 2004, graphs depicting socio-economic and Earth system trends from 1750 to 2000 were first published, revealing a dramatic upsurge and aptly termed “The Great Acceleration” (Steffen et al., 2004).

The Great Acceleration described the exponential growth dynamics that occurred after the Industrial Revolution, which led to a surge in productivity in the mode of production and a significant increase in material wealth. At the same time, but to a much lesser extent, there was a massive increase in natural resource consumption and emissions. Socio-economic growth went hand in hand with the acceleration of biophysical trends. Figures 6 and 7 describe some examples of important biophysical and socio-economic indicators, all of which start to increase with the Industrial Revolution. From the middle of the 20th century, the trend towards exponential growth becomes apparent.

::: {.callout-tip collapse="true" appearance="minimal"}
#### An illustration of exponential growth
The Wheat and Chessboard Problem is a mathematical problem often used to illustrate the concept of exponential growth. In the story, a servant asks the king to fill every square on a chessboard with grains of wheat, doubling the number on each square. Growth starts slowly, but with each doubling, the number of grains increases exponentially. By the 50th square, the number of rice grains would be large enough to cover Berlin’s 365-metre-high television tower on Alexanderplatz. This story illustrates the immense power of exponential growth and its impressive results. Understanding the concept of exponential growth is crucial to analysing phenomena such as population growth, technological progress, environmental change, and the spread of disease. It illustrates how even small changes or developments in a system can have a significant impact. History reminds us that we need to think carefully about how we manage such growth and the long-term consequences it can have.
:::

Resource extraction has increased significantly in recent decades, from 22 billion tonnes in 1970 to 70 billion tonnes in 2010 (UNEP, 2016). Global warming is another pressing issue. The latest IPCC report (IPCC, 2023) predicts an increase in global average temperature of between 1.5 and 5.8 degrees Celsius, depending on the scenario and future emissions. Another alarming phenomenon is deforestation. Every two seconds, an area of forest the size of a football field is cut down – an area the size of New York City every day. And then there is the decline in biodiversity, marked by the extinction of animal and plant species, which threatens the ecological diversity of our planet.
The Great Acceleration (Figures 6 and 7) describes the observable and measurable (negative) developments of key socio-economic and biophysical indicators since 1950. The causes of these negative developments can be far removed from the place where the problems arise or become most evident. For example, job losses in one country may be caused by a multinational company’s decision to relocate part of its operations to another country, in order to maximize profits. We cannot hope to fix such issues unless we understand how the system – in this case, the globalized economy – works. Similarly, we need to understand the Earth’s global climate systems to imagine what the consequences of global warming might be in a particular area or region.
This is why many of the methods and concepts of sustainability science require systemic thinking. A systemic thinking approach often begins with brainstorming to create a “rich picture” of all the factors you need to consider in order to understand the current behaviour of the system in question. For example, in the case of a multinational company closing a particular business unit, these would be the factors that might influence the decision to continue, expand, or close certain business units. While an initial mapping might look overly complex or even messy, creating a linear flowchart can help clarify the flows of inputs and influences. This kind of mapping may already reveal opportunities to reassess the relevant influences and redesign the system to avoid unwanted outcomes. However, further work may be required to develop “conceptual models” of the system that identify unforeseen opportunities for improvement.
Incorporating systemic thinking into the methods and concepts of sustainability science enables us to tackle the complexity of problems and develop sound strategies for sustainable development. Systemic thinking thus provides an important basis for understanding and shaping the different understandings and concepts of sustainable development, as the next chapter discusses in more detail.
