project:
  type: book

  output-dir: docs
  resources: 
    - "*.png"
    - "*.jpeg"
    - "*.jfif"
    - "*.svg"
    
execute:
  engine: knitr
  echo: false

book:
  title: "Basics of sustainability"
  subtitle: "Foundations and challenges of sustainability"
  cover-image: CoverLehrbuch.png
  favicon: images/
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true
  search: true
  site-url: https://cdeteaching.github.io/Basics-of-sustainability/
  repo-actions: [issue]
  
  sidebar:
    search: true
    logo: images/cdelogo_e.png
    tools:
      - icon: file-earmark-pdf
        href: https://github.com/CDEteaching/Basics-of-sustainability/blob/master/pdf/Basics-of-sustainability.pdf
        text: "Course Script (PDF)"
      - icon: bug
        href: https://github.com/CDEteaching/Basics-of-sustainability/issues/new
        text: "Report issue"
    
  page-footer:
    border: true
    left: |
      "This a product of <a href="www.cde.unibe.ch/">![](/images/cdelogo_e.png){style='width: auto; height: 35px; padding-left: 10px; padding-right: 10px; margin-bottom:5px;'}</a>
    center: |
      
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>. This work is licensed under a [CC-BY-NC-ND 4.0 Int License](https://creativecommons.org/licenses/by-nc-nd/4.0/).

  
  chapters:
  - index.qmd
  - intro.qmd
  - part: "Foundations"
    chapters:
    - 1_understanding/1_intro.qmd
  - part: "Approaches to Sustainability" 
    chapters: 
    - 2_approaches/2_intro.qmd
  - part: "Transforming (Un-)sustainable Systems: Key Areas and Strategic Approaches"
    chapters:
    - 3_ecological-sustainability/3_intro.qmd
    - 4_social-sustainability/4_intro.qmd
    - 5_economic-sustainability/5_intro.qmd
  - references.qmd

bibliography: references.bib

number-depth: 3

format:
  html:
    cover-image: CoverLehrbuch.png
    mainfont: Roboto
    monofont: Fira Code
    highlight-style: arrow
    monobackgroundcolor: "#F7F7F7"
    theme:
      light: [theme.scss]
      dark: [darkly]
    toggle: true
    default-mode: dark
    callout-icon: false
    css: webex.css
    include-after-body: webex.js
    df-print: kable
    
  
  pdf:
    output-file: SP_BasicSustainability
  # render pdf to separate folder -> do it manually via terminal
  # "quarto render SP_BasicSustainability.qmd --to pdf --output-dir pdf --output SP_BasicSustainability.pdf"
    title: BASICS OF SUSTAINABILITY
    documentclass: scrreprt
    classoption: ["oneside", "openany"]
    cover-image: CoverLehrbuch.png

    mainfont: "Alegreya"
    sansfont: "Source Sans Pro"
    urlcolor: "blue"

    number-depth: 3
    papersize: a4
    fig-pos: "H"
    pdf-engine: xelatex
    callout-icon: false
    
    keep-tex: true
    tables: true
    include-in-header:
      text: |
        \usepackage{booktabs}
        \usepackage{longtable}
        \usepackage{microtype}
        \hyphenpenalty=10000
        \exhyphenpenalty=10000
        \usepackage{pdfpages}
        \usepackage[font=footnotesize,labelfont={footnotesize}]{caption}
        \renewcommand{\maketitle}{}
        \usepackage[skins]{tcolorbox}
        \makeatletter
        \pgfkeys{/tcb/breakable/.code=\relax}
        \makeatother

    include-before-body: 
      text: |
        \includepdf[pages=1]{CoverLehrbuch.pdf}



