# Introduction

Amid the mounting challenges of sustainable development, Christo and Jeanne-Claude’s “Wrapped Globe” is a powerful symbol of humanity’s responsibility towards our planet and its resources. The artwork depicts a globe wrapped in transparent plastic and a filigree net. Meanwhile, in real life, the world is facing a “polycrisis” – the word used to describe the many serious crises our Earth is facing, including ecological crises, growing inequality, excessive national debt, and the effects of the Covid-19 pandemic, to name but a few. In a polycrisis, crises are increasingly intertwined and mutually reinforcing [@tooze2022], and they are mainly caused by a structural dependence on growth (as measured by gross domestic product, GDP) (Hickel et al., 2022; Sennholz, 2021); a vicious circle of ever-increasing concentration of economic and political power in the hands of a few (Piketty, 2014); and persistent inequalities between and within countries (Chancel et al., 2021; Milanovic, 2016). And yet, we keep striving for GDP growth in our society and our economy, in order to maintain and create jobs, finance our social security systems, secure tax revenues, and fulfil the needs of companies and industries that depend on growth to exist. As these expectations become increasingly unrealistic, the idea of decoupling economic growth from resource consumption has gained traction. However, there is no empirical evidence that doing so will achieve anywhere near the scale required to halt multidimensional ecological collapse (Parrique et al., 2019; Hickel and Kallis, 2020; Wiedmann et al., 2020).

## Full and empty world

The plastic cover and the net wrapped around Christo’s globe thus represent the interconnectedness and interdependence of the Earth’s various elements, and emphasize the need to maintain and preserve these relationships. A similar idea was described by the economist Herman Daly (2015), who put forth a concept of the “empty” and the “full” world. The empty world describes a situation in which human activities and resource use have only a minor impact on the environment. In this world, natural systems are still intact and untouched, and resources are sufficient to meet human needs. This contrasts with the full world, in which human activities and resource use overload the ecosystem and pollute the environment. Since at least the Second World War, we have pursued an industrialized society and a growth economy. As a result, we now live in a “full” world, where natural resources are scarce and the balance of ecosystems is under threat. Daly’s epiphany came in 1962 upon reading Rachel Carson’s book, Silent Spring, which called for a life in harmony with nature. Daly was already sceptical about the hyper-individualism of economic models, and Carson’s work highlighted the conflict between a growing economy and a fragile environment. Following a lecture by the economist Nicholas Georgescu-Roegen on his magnum opus, The Entropy Law and the Economic Process (1971), Daly adopted the idea that the economy was more like an hourglass than a pendulum, with valuable resources turning into waste and thus largely irreversibly lost. There is no master plan to counter the polycrisis and make our economic and social system more sustainable.

## This book

To contribute to sustainable development, we need to analyse the causes of symptoms such as biodiversity loss or global warming, and learn to understand how they are connected and how they interact. We will therefore look at current problems and challenges such as global warming, pollution, biodiversity loss, social inequality, and economic disparities, to understand how they can be tackled at both the local and the global level. The aim of this textbook is to encourage readers to think critically about the role of individuals, communities, businesses, and governments in the context of sustainable development – and thus to identify and pursue approaches to support sustainable development. In addition, we want to develop visions of the future, especially in the Master’s study programmes, that make it possible to imagine a high quality of life in a sustainable modern age, and that make changing the present seem attractive rather than daunting. We want to envision a different food culture, a different economic system, a different type of land use, and a different way of building and living. To make progress towards sustainability, it will be critical to engage stakeholders and foster collaboration across sectors and disciplines. As this textbook will emphasize, education, communication, and participation will also be indispensable in shaping a more sustainable future. With Christo’s Wrapped Globe in mind, and Daly’s understanding of the empty and the full world as a foundation, we will embark on a journey through the many aspects of sustainable development. We hope that you will find this journey both informative and inspiring, and that it will give you an understanding of both the urgency and the opportunities for sustainable development.

Finally, we hope that our study programmes will inspire students to reflect on their own roles and responsibilities in relation to sustainability, and that it will equip you to make a difference to ensure that the Earth remains a place worth living in for future generations. Only together can we bring about the changes needed to create a sustainable, just, and environmentally friendly world.
